### ISSUE TITLE
Pagination for firebase listeners

### ISSUE THREAD

**Issue by ibeckermayer** [covid19risk/permission-portal#182]
To prepare for organizations with larger numbers of users, we need to implement pagination for our firestore listeners. With our current code, we are simply downloading and then listening for updates on all users of an organization. However with larger organizations, this will end up eating up a lot of cpu/bandwidth unnecessarily. We should therefore implement something like this: 

https://medium.com/@650egor/firestore-reactive-pagination-db3afb0bf42e

**Comment by aidan-fitz** [comment]
I think we first need to define the behavior of the member table and how pagination will interact with it. The table should definitely be sorted (e.g. by last name or email address). However, if the users are sorted by last name, users can be inserted or deleted at any position in the table; our implementation of paginated load and update would have to take that into account.

For example, suppose that the page size is 10 and our members are named A...T (so that member A is at index 0, member B is at position 1, etc.). Our user first sees the first page consisting of users 0-9 (A, B, ..., J), then navigates to the next page consisting of users 10-19 (K...T). Then, another admin creates user Ev, which is inserted at position 5 (between E and F), and all subsequent users are bumped back one position so that user J is at position 10. Should the current page update to display users J-S or stay as K-T? If the user then navigates back to the first page, should they see A-I (the first ten users) or B-J (the ten users preceding K)? Maybe requiring the user to refresh the table in order to see updates will avoid this complexity.

Also worth considering: How often will users be added or deleted, relative to how often people will be viewing this page?

**Comment by ibeckermayer** [comment]
Good points/questions.

> The table should definitely be sorted (e.g. by last name or email address)
Let's go with last name, by convention

As for the rest of your question, the ideal is for all the clients to be an accurate representation of database at all times (including pagination). As you point out, with users sorted by last name this creates an issue not handled in the [linked Medium post](https://medium.com/@650egor/firestore-reactive-pagination-db3afb0bf42e), where a new user can shift the definition of the pages. 

If we were to try and implement the list of listeners in a manner that accounts for this, things quickly begin to get quite complex (i.e. we might introduce page listeners that cause cascading updates to the other listeners if a user is added or deleted, causing the pages to change. But then we can expect performance issues that must be addressed to account for when the admin is looking at page 400 and user Adam Adamson is added.). OTOH if we throw away listening for real time updates entirely, we introduce complexity in keeping the frontend congruent with the data. For example any time a user setting is changed, or a user is added or deleted, etc., we would need to manually query the database in order to update the frontend. We also introduce some new awkward edge cases, such as a user who has been deleted being updated, which causes the db to update and then the user disappears.

I think we can simplify this problem significantly and keep our "one way data-flow" by making the page a global variable and attaching a single listener for that page that keeps a client-side list of all the users in that page up to date with it. Then, when we switch pages, we simply throw out the previous list and listener, and set up new ones.

**Comment by ibeckermayer** [comment]
Tech design decided [in Slack](https://covid-watch.slack.com/archives/C013MKUMZK3/p1591399870300700)
